name: build-and-publish-image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # allow pushing to ghcr.io with the built-in token
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # image name must be lowercase for ghcr
          tags: |
            ghcr.io/arpit369/apigee-backend-test:latest
            ghcr.io/arpit369/apigee-backend-test:${{ github.sha }}
